import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="app-container">
          <header className="status-bar">
            <div className="logo">
              <span className="icon">🌿</span>
              <h1>Greenhouse<span className="highlight">Pico</span></h1>
            </div>
            <nav style={{ display: 'flex', gap: '20px' }}>
              <Link href="/" className="btn-toggle">
                <span className="btn-icon">🏠</span>
                <span className="btn-text">Home</span>
              </Link>
              <Link href="/testArea" className="btn-toggle">
                <span className="btn-icon">🧪</span>
                <span className="btn-text">Test Area</span>
              </Link>
              <Link href="http://100.85.165.95/huset/" className="btn-toggle" target="_blank">
                <span className="btn-icon"><img src="/plane.png" /></span>
                <span className="btn-text">Plane</span>
              </Link>
              <Link href="/surveillance" className="btn-toggle">
                <span className="btn-icon">👁️</span>
                <span className="btn-text">Surveillance</span>
              </Link>
              {/* New Business Analyzer Link */}
              <Link href="/businessAnalyzer" className="btn-toggle">
                <span className="btn-icon">📊</span>
                <span className="btn-text">Business Analyzer</span>
              </Link>
              <Link href="http://localhost:18789" className="btn-toggle" target="_blank">
                <span className="btn-icon">🧘</span>
                <span className="btn-text">Jedi Wigga</span>
              </Link>
            </nav>
            <div className="connection-status">
              <div className="status-dot"></div>
              <span>System Active</span>
            </div>
          </header>
          {children}  {/* This is your page content */}
          <footer>
            <section className="card test-card">
              <h2>Footer</h2>
            </section>
          </footer>
        </div>
      </body>
    </html>
  );
}